-- Waitlist capture for BC Pay Gap Report
-- Created: 2026-03-10

CREATE TABLE waitlist_signups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  company TEXT NOT NULL,
  employee_band TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  source TEXT,
  referrer TEXT,
  user_agent TEXT
);

CREATE INDEX idx_waitlist_signups_created_at ON waitlist_signups(created_at);
CREATE INDEX idx_waitlist_signups_email ON waitlist_signups(email);

CREATE TABLE waitlist_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_name TEXT NOT NULL,
  event_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  metadata JSONB DEFAULT '{}'::JSONB
);

CREATE INDEX idx_waitlist_events_name ON waitlist_events(event_name);
CREATE INDEX idx_waitlist_events_event_at ON waitlist_events(event_at);

ALTER TABLE waitlist_signups ENABLE ROW LEVEL SECURITY;
ALTER TABLE waitlist_events ENABLE ROW LEVEL SECURITY;

-- Inserts happen via service role in API routes; no anon policies.
